default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

  host: ec2-107-22-234-204.compute-1.amazonaws.com
  username: exhkgjwlgmaxmo
  password: e7519deebf430c602f4f11fb41c416621289827951d738132198f956d81b700e
  database: d8o95m9aopuqvh
  port: 5432

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default